# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: profile.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'profile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprofile.proto\x12\x07profile\"!\n\x0eProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"?\n\x0fProfileResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t2Q\n\x0eProfileService\x12?\n\nGetProfile\x12\x17.profile.ProfileRequest\x1a\x18.profile.ProfileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROFILEREQUEST']._serialized_start=26
  _globals['_PROFILEREQUEST']._serialized_end=59
  _globals['_PROFILERESPONSE']._serialized_start=61
  _globals['_PROFILERESPONSE']._serialized_end=124
  _globals['_PROFILESERVICE']._serialized_start=126
  _globals['_PROFILESERVICE']._serialized_end=207
# @@protoc_insertion_point(module_scope)
